Add Posterior Standard Deviation acquisition function
pytorch/botorch pull request #2060
Opened 2023-10-19 07:56 UTC by pjpollot

## Motivation

I am a machine learning engineer actively researching Bayesian optimization solutions to apply in my company's products. Lately, I've been trying to find the right balance between exploitation and exploration by incorporating pure exploration into a sequential batch Bayesian optimization algorithm. `qNegIntegratedPosteriorVariance` was a suitable choice for this purpose, but it proved a bit slower when compared to the Posterior Standard Deviation acquisition function that I'm introducing in this pull request.

The acquisition function simply returns the posterior standard deviation of the Gaussian process model, so the time complexity remains relatively low when compared to a Monte Carlo acquisition function.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/pytorch/botorch/blob/main/CONTRIBUTING.md#pull-requests)?

Yes. I just get an error every time I try to submit the CLA...
If someone could help me. 

## Test Plan

`PosteriorStandardDeviation` class I implemented is extremely similar to `PosteriorMean`, so the implementation and the unit tests also look almost the same. I just made sure to define a variance for `MockPosterior` in order to effectively run the unit tests. 

As I may have some doubts about batch unit testing in order to verify if my solution only applies for `q=1`, I would be glad to hear it from you about my current implementation!  

PS: I guess there is no problem with the integration of the new acquisition function in the documentation! ⬇️

<img width="809" alt="doc screenshot" src="https://github.com/pytorch/botorch/assets/47068641/52e2cdb2-806c-4718-8c0d-63f7a0ac8efb">

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/pytorch/botorch, and link to your PR here.)

2023-10-19 17:37 UTC, Balandat commented
Thanks for the PR - are there any results on / benchmarks for this acquisition function or suggestions how to best use it? I want to make sure that everything we expose in the core package has been evaluated rigorously and that users can have (or at least develop, e.g. from reading papers) if and when to use a particular acquisition function.

Also, looks like there are a bunch of auto-formatting changes that snuck into the commit?

2023-10-20 00:18 UTC, pjpollot commented
@Balandat 
Thank you for your quick reply!

> are there any results on / benchmarks for this acquisition function or suggestions how to best use it?
No, nothing I could present as of now to promote the use of this acquisition function, but I wish to be able to show you some promising results once my research on the subject is done. 

> Also, looks like there are a bunch of auto-formatting changes that snuck into the commit?
Yes, I just run the command `ufmt format .` like suggested in CONTRIBUTING.md, but surprisingly several files other than the ones I modified got changed as well.

2023-10-20 00:22 UTC, Balandat commented
> No, nothing I could present as of now to promote the use of this acquisition function, but I wish to be able to show you some promising results once my research on the subject is done.

I see. I'd like to see some of these results / pointers before merging this in.

> Yes, I just run the command ufmt format . like suggested in CONTRIBUTING.md, but surprisingly several files other than the ones I modified got changed as well.

Hmm interesting, maybe there was a recent `ufmt` version bump. What `ufmt` version is installed in your environment?

2023-10-20 01:14 UTC, pjpollot commented
@Balandat 
No problem, I will finish my research first and get back to you with some results!
The `ufmt` version I am using is `2.3.0`.

2023-10-20 03:14 UTC, eytan commented
Pierre-Jean, thanks for the PR!
No need to use your own data—you can just run it on a couple of the
synthetic benchmark functions like hartman6 already in botorch! It’s  much
simpler and more replicable this way anyways.  In general I’d highly
recommend such a validation pipeline for any new active learning or BO
procedures before using them with real data.

E

On Thu, Oct 19, 2023 at 9:15 PM Pierre-Jean Pollot ***@***.***>
wrote:

> @Balandat <https://github.com/Balandat>
> No problem, I will finish my research first and get back to you with some
> results!
> The ufmt version I am using is 2.3.0.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pytorch/botorch/pull/2060#issuecomment-1771919057>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAW34MWFVB3Z5BK2ET7NADYAHGB3AVCNFSM6AAAAAA6GXV3IGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZRHEYTSMBVG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-10-21 04:06 UTC, pjpollot commented
Thank you very much for your feedback. 

I send you below the scripts and graphs for Ackley1D and (negate) Styblinski-tang1D to visualize the behavior of `PosteriorStandardDeviation` acquisition function.

<details><summary>Scripts</summary><div>
Main script: 
```python
import json

from typing import Any

from warnings import filterwarnings

import torch

from botorch.acquisition import PosteriorStandardDeviation
from botorch.fit import fit_gpytorch_model
from botorch.models import SingleTaskGP
from botorch.optim import optimize_acqf
from botorch.test_functions import Ackley, StyblinskiTang
from botorch.test_functions.synthetic import SyntheticTestFunction
from botorch.utils.transforms import unnormalize
from gpytorch.kernels import MaternKernel, ScaleKernel

from gpytorch.mlls import ExactMarginalLogLikelihood
from torch import Tensor


class Benchmark1D:
    def __init__(self, synthetic_function: SyntheticTestFunction) -> None:
        assert synthetic_function.dim == 1, "Benchmark1D is only for 1D functions"
        self._func = synthetic_function
        self._name = synthetic_function.__class__.__name__.lower() + "1d"

    @property
    def name(self) -> str:
        return self._name

    @property
    def bounds(self) -> Tensor:
        return self._func.bounds

    def __call__(self, x: Tensor) -> Tensor:
        return self._func(x).unsqueeze(-1)

    def sample(self, n: int) -> tuple[Tensor, Tensor]:
        z = torch.rand(n, 1)
        x = unnormalize(z, self.bounds)
        return x, self(x)

    def linspace(self, n: int) -> tuple[Tensor, Tensor]:
        z = torch.linspace(0, 1, n).unsqueeze(-1)
        x = unnormalize(z, self.bounds)
        return x, self(x)


def pure_exploration(model: SingleTaskGP, bounds: Tensor) -> Tensor:
    acq_func = PosteriorStandardDeviation(model)
    return optimize_acqf(
        acq_function=acq_func,
        bounds=bounds,
        q=1,
        num_restarts=10,
        raw_samples=512,
    )[0]


def build_train_gp_model(x: Tensor, y: Tensor) -> SingleTaskGP:
    model = SingleTaskGP(
        train_X=x,
        train_Y=y,
        covar_module=ScaleKernel(MaternKernel(nu=1.5)),
    )
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    return model

def to_list(t: Tensor) -> list:
    return t.detach().squeeze().tolist()


N_INIT = 2
MAX_SIZE = 100
SYNTHETIC_FUNCTIONS = [
    Ackley(dim=1),
    StyblinskiTang(dim=1, negate=True),
]

if __name__ == "__main__":
    filterwarnings("ignore")
    res = {}
    for function in SYNTHETIC_FUNCTIONS:
        torch.manual_seed(0)
        benchmark = Benchmark1D(function)
        print(benchmark.name)
        x, y = benchmark.sample(N_INIT)
        x_test, y_test = benchmark.linspace(1000)
        res[benchmark.name] = {
            "test_x": to_list(x_test),
            "test_y": to_list(y_test),
            "loop": [],
        }
        while x.shape[0] < MAX_SIZE:
            if x.shape[0] % 10 == 0:
                print(x.shape[0], "/", MAX_SIZE)
            model = build_train_gp_model(x, y)
            x_next = pure_exploration(model, benchmark.bounds)
            y_next = benchmark(x_next)
            posterior = model(x_test)
            mean = posterior.mean
            rmse = compute_rmse(y_test, mean)
            std = posterior.stddev
            bottom, top = posterior.confidence_region()
            res[benchmark.name]["loop"].append(
                {
                    "x": to_list(x),
                    "y": to_list(y),
                    "x_next": to_list(x_next),
                    "mean": to_list(mean),
                    "std": to_list(std),
                    "bottom": to_list(bottom),
                    "top": to_list(top),
                }
            )
            x = torch.cat([x, x_next])
            y = torch.cat([y, y_next])

        with open("results.json", "w") as f:
            json.dump(res, f, indent=2)
```

Visualization script: 
```python
import json
import os

import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    plt.style.use("ggplot")
    with open("results.json", "r") as f:
        res = json.load(f)
    for benchmark_name, benchmark_res in res.items():
        print(benchmark_name)
        folder = f"graphs/{benchmark_name}"
        os.makedirs(folder, exist_ok=True)
        for i, loop in enumerate(benchmark_res["loop"]):
            fig, (ax1, ax2) = plt.subplots(
                nrows=2, figsize=(5, 10), sharex=True, constrained_layout=True
            )
            fig.suptitle(benchmark_name)
            ax1.plot(
                benchmark_res["test_x"], benchmark_res["test_y"], "--", label="true"
            )
            ax1.plot(benchmark_res["test_x"], loop["mean"], label="predicted")
            ax1.fill_between(
                benchmark_res["test_x"],
                loop["bottom"],
                loop["top"],
                alpha=0.5,
            )
            ax1.scatter(loop["x"], loop["y"], label="training data")
            ax1.axvline(loop["x_next"], color="black", label="next query point")
            ax1.fill_between(
                benchmark_res["test_x"],
                loop["bottom"],
                loop["top"],
                alpha=0.5,
                label="confidence region",
            )
            ax2.plot(benchmark_res["test_x"], loop["std"])
            ax2.axvline(loop["x_next"], color="black")
            ax1.set_title(f"{len(loop['x'])} training points")
            ax1.legend(loc="lower left")
            ax1.set_ylabel("y")
            ax2.set_ylabel("std")
            ax2.set_xlabel("x")
            fig.savefig(os.path.join(folder, f"{i+1}.png"))
            plt.close(fig)
```
</div></summary>

<details><summary>Graphs</summary><div>
![ackley1d](https://github.com/py
![styblinskitang1d](https://github.com/pytorch/botorch/assets/47068641/3feb35c9-852d-48ea-b5f3-e890706c1067)
torch/botorch/assets/47068641/3ab835fc-c050-4351-b018-295a8c2b1ec8)
</div></summary>

2023-10-21 04:10 UTC, pjpollot commented
```python
import json

from typing import Any

from warnings import filterwarnings

import torch

from botorch.acquisition import PosteriorStandardDeviation
from botorch.fit import fit_gpytorch_model
from botorch.models import SingleTaskGP
from botorch.optim import optimize_acqf
from botorch.test_functions import Ackley, StyblinskiTang
from botorch.test_functions.synthetic import SyntheticTestFunction
from botorch.utils.transforms import unnormalize
from gpytorch.kernels import MaternKernel, ScaleKernel

from gpytorch.mlls import ExactMarginalLogLikelihood
from torch import Tensor


class Benchmark1D:
    def __init__(self, synthetic_function: SyntheticTestFunction) -> None:
        assert synthetic_function.dim == 1, "Benchmark1D is only for 1D functions"
        self._func = synthetic_function
        self._name = synthetic_function.__class__.__name__.lower() + "1d"

    @property
    def name(self) -> str:
        return self._name

    @property
    def bounds(self) -> Tensor:
        return self._func.bounds

    def __call__(self, x: Tensor) -> Tensor:
        return self._func(x).unsqueeze(-1)

    def sample(self, n: int) -> tuple[Tensor, Tensor]:
        z = torch.rand(n, 1)
        x = unnormalize(z, self.bounds)
        return x, self(x)

    def linspace(self, n: int) -> tuple[Tensor, Tensor]:
        z = torch.linspace(0, 1, n).unsqueeze(-1)
        x = unnormalize(z, self.bounds)
        return x, self(x)


def pure_exploration(model: SingleTaskGP, bounds: Tensor) -> Tensor:
    acq_func = PosteriorStandardDeviation(model)
    return optimize_acqf(
        acq_function=acq_func,
        bounds=bounds,
        q=1,
        num_restarts=10,
        raw_samples=512,
    )[0]


def build_train_gp_model(x: Tensor, y: Tensor) -> SingleTaskGP:
    model = SingleTaskGP(
        train_X=x,
        train_Y=y,
        covar_module=ScaleKernel(MaternKernel(nu=1.5)),
    )
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    return model

def to_list(t: Tensor) -> list:
    return t.detach().squeeze().tolist()


N_INIT = 2
MAX_SIZE = 100
SYNTHETIC_FUNCTIONS = [
    Ackley(dim=1),
    StyblinskiTang(dim=1, negate=True),
]

if __name__ == "__main__":
    filterwarnings("ignore")
    res = {}
    for function in SYNTHETIC_FUNCTIONS:
        torch.manual_seed(0)
        benchmark = Benchmark1D(function)
        print(benchmark.name)
        x, y = benchmark.sample(N_INIT)
        x_test, y_test = benchmark.linspace(1000)
        res[benchmark.name] = {
            "test_x": to_list(x_test),
            "test_y": to_list(y_test),
            "loop": [],
        }
        while x.shape[0] < MAX_SIZE:
            if x.shape[0] % 10 == 0:
                print(x.shape[0], "/", MAX_SIZE)
            model = build_train_gp_model(x, y)
            x_next = pure_exploration(model, benchmark.bounds)
            y_next = benchmark(x_next)
            posterior = model(x_test)
            mean = posterior.mean
            rmse = compute_rmse(y_test, mean)
            std = posterior.stddev
            bottom, top = posterior.confidence_region()
            res[benchmark.name]["loop"].append(
                {
                    "x": to_list(x),
                    "y": to_list(y),
                    "x_next": to_list(x_next),
                    "mean": to_list(mean),
                    "std": to_list(std),
                    "bottom": to_list(bottom),
                    "top": to_list(top),
                }
            )
            x = torch.cat([x, x_next])
            y = torch.cat([y, y_next])

        with open("results.json", "w") as f:
            json.dump(res, f, indent=2)
```

2023-10-21 04:11 UTC, pjpollot commented
Visualization script: 

```python
import json
import os

import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    plt.style.use("ggplot")
    with open("results.json", "r") as f:
        res = json.load(f)
    for benchmark_name, benchmark_res in res.items():
        print(benchmark_name)
        folder = f"graphs/{benchmark_name}"
        os.makedirs(folder, exist_ok=True)
        for i, loop in enumerate(benchmark_res["loop"]):
            fig, (ax1, ax2) = plt.subplots(
                nrows=2, figsize=(5, 10), sharex=True, constrained_layout=True
            )
            fig.suptitle(benchmark_name)
            ax1.plot(
                benchmark_res["test_x"], benchmark_res["test_y"], "--", label="true"
            )
            ax1.plot(benchmark_res["test_x"], loop["mean"], label="predicted")
            ax1.fill_between(
                benchmark_res["test_x"],
                loop["bottom"],
                loop["top"],
                alpha=0.5,
            )
            ax1.scatter(loop["x"], loop["y"], label="training data")
            ax1.axvline(loop["x_next"], color="black", label="next query point")
            ax1.fill_between(
                benchmark_res["test_x"],
                loop["bottom"],
                loop["top"],
                alpha=0.5,
                label="confidence region",
            )
            ax2.plot(benchmark_res["test_x"], loop["std"])
            ax2.axvline(loop["x_next"], color="black")
            ax1.set_title(f"{len(loop['x'])} training points")
            ax1.legend(loc="lower left")
            ax1.set_ylabel("y")
            ax2.set_ylabel("std")
            ax2.set_xlabel("x")
            fig.savefig(os.path.join(folder, f"{i+1}.png"))
            plt.close(fig)
```

2023-10-23 15:07 UTC, esantorella commented
This is very related to an extensive previous discussion on maximum variance acquisition functions for active learning (#1366 ). A `(q)MaximumVariance` acquisition function was proposed there. The discussion was a bit long and hard to summarize, but I think there was some tension between wanting to test that maximum variance works well before incorporating it vs. wanting to have it available regardless since it's commonly used as a baseline in active learning applications. I propose consolidating discussion on #1366 .

2023-10-23 21:46 UTC, esantorella commented on test/acquisition/test_analytic.py
> +            with self.assertRaises(UnsupportedError):
It would be ideal to use `assertRaisesRegex` to check that the error message is as expected.

2023-10-23 21:47 UTC, esantorella commented on test/acquisition/test_analytic.py
> +            module = PosteriorStandardDeviation(model=mm)
Nit: It would be more conventional and clearer to rename `module` to `acqf`, since `module` is very generic

2023-10-23 21:48 UTC, esantorella commented on botorch/acquisition/analytic.py
> +                actually returns -1 * minimum of the posterior standard deviation.
Thanks for the clear docstring! It would be even better to include an example of how to use this

2023-10-23 21:50 UTC, esantorella requested changes
Thanks so much for putting this in! I'm happy to approve this once the formatting changes to irrelevant files are reverted.

2023-10-24 14:12 UTC, esantorella approved these changes
Thanks!

2023-10-25 02:00 UTC, saitcakmak commented on botorch/acquisition/analytic.py
> +    `stddev` property. The model must be single-outcome.
```suggestion
    Only supports the case of q=1. Requires the model's posterior to have
    `mean` and `variance` properties. The model must be either single-outcome
    or combined with a `posterior_transform` to produce a single-output posterior.
```

2023-10-25 04:36 UTC, closed without merging

2023-10-25 14:12 UTC, esantorella commented on botorch/acquisition/analytic.py
> +        >>> PSTD = PosteriorMean(model)
This should be `PosteriorStandardDeviation` right? I'll put in a quick fix.