bump to minimum python version to 3.10 and test 3.12
pytorch/botorch pull request #2293
Opened 2024-04-10 21:57 UTC by sdaulton

## Motivation
Bump minimum version of python from 3.9 -> 3.10 and start testing 3.12, since scientific python is no longer supporting py3.9: https://scientific-python.org/specs/spec-0000/

### Have you read the [Contributing Guidelines on pull requests](https://github.com/pytorch/botorch/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

Circle CI

2024-04-10 22:33 UTC, saitcakmak requested changes

2024-04-10 22:33 UTC, saitcakmak commented on .github/workflows/deploy_on_release.yml
> +        python-version: ["3.10", "3.11", "3.12"]
We test oldest & newest supported versions. No need to spend extra compute on 3.11.

2024-04-10 22:33 UTC, saitcakmak commented on .github/workflows/deploy_on_release.yml
Github won't let me comment there but there's another python-version 3.9 on line 49

2024-04-10 22:33 UTC, saitcakmak commented on setup.py
> +    python_requires=">=3.10",
Avoids the need for future updates
```suggestion
    python_requires=f">={REQUIRED_MAJOR}.{REQUIRED_MINOR}",
```

2024-04-11 00:30 UTC, saitcakmak commented
Looks like there are 3 tutorial failures. Two of them should be resolved once the Ax PR lands. The last one seems to originate from the `cma` package. It might require an upstream fix before we can land this -- or we can temporarily disable that tutorial.

2024-04-11 01:04 UTC, saitcakmak commented
I looked into this a bit more closely. Looks like the failures happen because we're using development version of numpy 2.0 (installed with torch nightly), which changes some things with the copy kwarg.

2024-04-11 01:11 UTC, Balandat commented
@saitcakmak we don't need to use the numpy 2.0 dev version though, right? Or do the torch nightlies depend on it? If not we should be able to install numpy <2.0 first and then the torch nightlies in CI

2024-04-11 16:48 UTC, saitcakmak commented
I am guessing numpy 2.0 rc1 gets installed because the install command for pytorch nightly is `pip install --pre ...`. If `--pre` is not necessary, removing it could fix the issue without having to pin numpy. I recall this causing an issue with another dependency in the recent past

2024-04-11 16:58 UTC, Balandat commented
Yeah that's definitely the reason it gets installed. But if we manually install numpy (without the `--pre` option) prior to installing torch, it shouldn't be upgrading numpy, even when installing torch with `--pre` option.

2024-04-11 17:02 UTC, saitcakmak commented
I think removing `--pre` (if it works) is a cleaner solution than pinning `numpy`. Both in that it will not add additional commands in various places, and it won't introduce code that needs to be cleaned up later. By the time numpy 2.0 is released, we should aim to be compatible with it -- which doens't require a lot of work, as I found in https://github.com/CMA-ES/pycma/pull/251. We likely have much less `numpy` code than cma does.

2024-04-11 17:31 UTC, sdaulton commented
removing pre did the trick.

2024-04-11 17:37 UTC, Balandat requested changes

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/nightly.yml
> +        python-version: ["3.10", "3.11", "3.12"]
let's not test 3.11 here? If things work for 3.10 and 3.12 they should also work for 3.11. And having 3.11 here will cost a bunch of GHA capacity (note that macos hosts are more expensive)

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/nightly.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/test.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/test.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/test_stable.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/test_stable.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:37 UTC, Balandat commented on .github/workflows/test_stable.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:40 UTC, saitcakmak approved these changes

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/nightly.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/reusable_tutorials.yml
> +      # Ax and cma are not compatible with numpy 2.0 yet
```suggestion
```

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/test.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/test.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/test_stable.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/test_stable.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 17:40 UTC, saitcakmak commented on .github/workflows/test_stable.yml
> +        python-version: ["3.10", "3.11", "3.12"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-04-11 18:50 UTC, closed without merging